### ISSUE TITLE
Not working without internet connection

### ISSUE THREAD

**Issue by Tulakshana** [Uepaa-AG/p2pkit-quickstart-android#11]
I can't get this to work with no internet connection. I think it is trying to validate by app key all the time even though their developer centre tells me otherwise.

<img width="787" alt="screen shot 2018-06-21 at 2 09 43 pm" src="https://user-images.githubusercontent.com/1791770/41745819-1ffd0652-755d-11e8-8121-de8133ddb688.png">

**Comment by uepaa** [comment]
As discussed in the PM earlier today, p2pkit needs internet connection in order to operate. The whole discovery management is handled in the cloud to allow best local p2p discovery at scale and at speed. Check our benchmark test for further information: http://blog.p2pkit.io/p2pkit-2-0-beta-benchmarking/
